apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service-app-uat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: application-service-app-uat
    spec:
      serviceAccountName: irsaappservice
      containers:
        - name: application-service
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cica/cica-repo-uat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3110
          env:
            - name: APPLICATION_QUEUE_ID
              valueFrom:
                secretKeyRef:
                  name: application-sqs
                  key: sqs_id
            - name: TEMPUS_QUEUE_ID
              valueFrom:
                secretKeyRef:
                  name: tempus-sqs
                  key: sqs_id
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: kta_s3_bucket
            - name: KMS_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: kta_s3_kms_id
  selector:
    matchLabels:
      app: application-service-app-uat
