apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service-app-stag
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: application-service-app-stag
    spec:
      containers:
        - name: application-service
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cica/cica-repo-stag:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3110
          env:
            - name: APPLICATION_QUEUE_ID
              valueFrom:
                secretKeyRef:
                  name: application-sqs
                  key: sqs_id
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-service-sqs-secret
                  key: access_key_id
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-service-sqs-secret
                  key: secret_access_key
            - name: TEMPUS_QUEUE_ID
              valueFrom:
                secretKeyRef:
                  name: tempus-sqs
                  key: sqs_id
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: kta_s3_bucket
            - name: KMS_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: kta_s3_kms_id
  selector:
    matchLabels:
      app: application-service-app-stag
