apiVersion: v1
kind: Service
metadata:
  name: application-service-stag
  labels:
    app: application-service-app-stag
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3110
  selector:
    app: application-service-app-stag
